testListData function is extended. It now loads data for a user who is an admin for at least two organizations.
Why is it different? Because the underlying query has IN filter with two options. The test fails with the following message:

Exception in request:
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/s~melange-dev-hrd/2-1-20140221-daniel.373976358957856942/soc/views/base.py", line 482, in __call__
    return self._dispatch(data, check, mutator)
  File "/base/data/home/apps/s~melange-dev-hrd/2-1-20140221-daniel.373976358957856942/soc/views/base.py", line 434, in _dispatch
    return self.json(data, check, mutator)
  File "/base/data/home/apps/s~melange-dev-hrd/2-1-20140221-daniel.373976358957856942/soc/views/base.py", line 134, in json
    context = self.jsonContext(data, check, mutator)
  File "/base/data/home/apps/s~melange-dev-hrd/2-1-20140221-daniel.373976358957856942/melange/views/connection.py", line 1072, in jsonContext
    self.url_names, self.template_path, data).getListData()
  File "/base/data/home/apps/s~melange-dev-hrd/2-1-20140221-daniel.373976358957856942/melange/templates/connection_list.py", line 76, in getListData
    return response_builder.buildNDB()
  File "/base/data/home/apps/s~melange-dev-hrd/2-1-20140221-daniel.373976358957856942/soc/views/helper/lists.py", line 1487, in buildNDB
    count, start_cursor=cursor)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/utils.py", line 142, in positional_wrapper
    return wrapped(*args, **kwds)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1325, in fetch_page
    return self.fetch_page_async(page_size, **q_options).get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 325, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 368, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1343, in _fetch_page_async
    while (yield it.has_next_async()):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 368, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1747, in has_next_async
    yield self._fut
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 814, in helper
    batch, i, ent = yield inq.getq()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 931, in run_to_queue
    yield multiquery.run_to_queue(queue, conn, options=options)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 371, in _help_tasklet_along
    value = gen.send(val)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1880, in run_to_queue
    '_MultiQuery with cursors requires __key__ order')
BadArgumentError: _MultiQuery with cursors requires __key__ order