Functions defined in connection view are now based on NDB model.
This is natural, because Connection model is not NDB based. For some unknown to me reason, tests for organization application passed. Does it mean that db transaction can manipulate NDB data? I do not think so. The operation could not be completed on localhost due to some strange error which was related to Django and I have no idea why it occurred.

Here is the error message:
ERROR    2014-01-20 18:12:50,529 api_server.py:183] Exception while handling service_name: "datastore_v3"
method: "Commit"
request: "\011\220\235}\017\001\000\000\000\022\022dev~google-melange"
request_id: "GossUfhWXT"

Traceback (most recent call last):
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 163, in _handle_POST
    api_response = _execute_request(request).Encode()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 124, in _execute_request
    make_request()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 116, in make_request
    request_id)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/datastore/datastore_sqlite_stub.py", line 946, in MakeSyncCall
    response, request_id)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/apiproxy_stub.py", line 130, in MakeSyncCall
    method(request, response)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/datastore/datastore_stub_util.py", line 3128, in _Dynamic_Commit
    res.mutable_cost().CopyFrom(txn.Commit())
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/datastore/datastore_stub_util.py", line 1387, in sync
    return function(txn, *args, **kwargs)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/datastore/datastore_stub_util.py", line 1647, in Commit
    trackers = self._GetAllTrackers()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/datastore/datastore_stub_util.py", line 1503, in _GetAllTrackers
    '__global__', 1, _app=self._app)._ToPb())
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/datastore_types.py", line 487, in from_path
    namespace = ResolveNamespace(namespace)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/datastore_types.py", line 245, in ResolveNamespace
    namespace = namespace_manager.get_namespace()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/namespace_manager/namespace_manager.py", line 87, in get_namespace
    name = _config.default_namespace_for_request()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/lib_config.py", line 353, in __getattr__
    self._update_configs()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/lib_config.py", line 289, in _update_configs
    self._registry.initialize()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/lib_config.py", line 164, in initialize
    import_func(self._modname)
  File "/Users/daniel/Documents/projects/soc/app/appengine_config.py", line 18, in <module>
    import gae_django
  File "/Users/daniel/Documents/projects/soc/app/gae_django.py", line 27, in <module>
    import django.db
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/lib/django-1.5/django/db/__init__.py", line 11, in <module>
    if settings.DATABASES and DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/lib/django-1.5/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/lib/django-1.5/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/lib/django-1.5/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/lib/django-1.5/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/daniel/Documents/projects/soc/app/settings.py", line 23, in <module>
    DEBUG = os.environ['SERVER_SOFTWARE'].startswith('Dev')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'SERVER_SOFTWARE'

ERROR    2014-01-20 18:12:50,588 gae_django.py:33] Exception in request:
Traceback (most recent call last):
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/lib/django-1.5/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/daniel/Documents/projects/soc/build/soc/views/base.py", line 475, in __call__
    return self._dispatch(data, check, mutator)
  File "/Users/daniel/Documents/projects/soc/build/soc/views/base.py", line 432, in _dispatch
    return self.post(data, check, mutator)
  File "/Users/daniel/Documents/projects/soc/build/summerofcode/views/org_app.py", line 520, in post
    user_role=connection_model.ROLE)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/datastore.py", line 2722, in inner_wrapper
    return RunInTransactionOptions(options, func, *args, **kwds)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/datastore.py", line 2620, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/datastore.py", line 2656, in _DoOneTry
    if _GetConnection().commit():
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2089, in commit
    return rpc.get_result()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 612, in get_result
    return self.__get_result_hook(self)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2112, in __commit_hook
    rpc.check_success()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 578, in check_success
    self.__rpc.CheckSuccess()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/apiproxy_rpc.py", line 156, in _WaitImpl
    self.request, self.response)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 200, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 234, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception())
RuntimeError: KeyError('SERVER_SOFTWARE',)

The problem is that we do set SERVER_SOFTWARE in the environment. Also, one connection was always successfully created. The error occurred for the second one, i.e. with a backup administrator. Was SERVER_SOFTWARE removed from os at some point? Was different os env used?

These are all interesting questions, but they are not relevant anymore, as this function changes DB and to NDB and the function works smoothly on both test and dev environments. I am attaching this stack trace for future reference if it happens again.