BadRequestError fixed for testPostPublish.
For some reason, as details of GCI dashboard tests are still mysterious to me, changes introduced in the previous revision brought about the following error for testPostPublish function:

BadRequestError: cross-groups transaction need to be explicitly specified (xg=True)

It is not clear why this error did not occur before, as there is no option the problem was caused by the previous change. It was there all over. Function publish_task_txn retrived a task (one entity group) and then called orgAdminFor which made other get() requests in order to retrive organization entities (other entity groups).

This revision consists of three changes:
- it explicitly marks publish_task_txn as transactional and set xg to True
- it simplifies the check if the user is an org admin for the specific org so that no extra RPC calls are required
- it retrives fresh profile entity before doing the check above so that the function is actually transaction safe