testAllAdminsAreSentEmails test case added.
It checks, what happens if the email is sent to more organization admins. A bit surprisingly to me, _ADMINS_NUMBER number cannot be greater than 3 (which means four admins). Otherwise, the following error message is printed.

It means that we cannot have more than 4 org admins per org. Or we have to schedule this tasks non-transactionally. I added the NOTE so that we are aware of the potential issue.

Traceback (most recent call last):
  File "/Users/daniel/Documents/projects/soc/tests/app/melange/logic/test_organization.py", line 350, in testAllAdminsAreSentEmails
    org_model.Status.ACCEPTED, org_admins=admins)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/ndb/utils.py", line 173, in inner_wrapper
    return wrapped_decorator(func, args, kwds, **options)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/ndb/model.py", line 3611, in transactional
    func, args, kwds, **options).get_result()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/ndb/tasklets.py", line 325, in get_result
    self.check_success()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/ndb/tasklets.py", line 371, in _help_tasklet_along
    value = gen.send(val)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/ndb/context.py", line 937, in transaction
    result = callback()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/ext/ndb/model.py", line 3619, in <lambda>
    return transaction_async(lambda: func(*args, **kwds), **options)
  File "/Users/daniel/Documents/projects/soc/app/melange/logic/organization.py", line 205, in setStatus
    parent=organization)
  File "/Users/daniel/Documents/projects/soc/app/melange/logic/profile.py", line 421, in dispatchOrgMemberWelcomeEmail
    program_messages.mentor_welcome_msg, context, parent=parent)()
  File "/Users/daniel/Documents/projects/soc/app/soc/tasks/mailer.py", line 99, in txn
    new_task.add(queue_name='mail', transactional=transactional)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/taskqueue/taskqueue.py", line 1132, in add
    return self.add_async(queue_name, transactional).get_result()
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 612, in get_result
    return self.__get_result_hook(self)
  File "/Users/daniel/Documents/projects/soc/thirdparty/google_appengine/google/appengine/api/taskqueue/taskqueue.py", line 1936, in ResultHook
    raise _TranslateError(e.application_error, e.error_detail)
JointException: taskqueue.DatastoreError caused by: <class 'google.appengine.api.datastore_errors.BadRequestError'> Too many messages, maximum allowed 5